#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /var/lib/purrito

        if getent passwd purrito >/dev/null; then
            deluser --quiet --system purrito || true
        fi
        if getent group purrito >/dev/null; then
            delgroup --quiet --system purrito || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
